on:
  workflow_call:
    inputs:
      azure-webapp-package-path:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      project-relative-path:
        required: true
        type: string
      dotnet-core-version:
        required: false
        type: string
        default: 7.0.x
      backend-root-path:
        required: false
        type: string
        default: src
      configuration:
        required: false
        type: string
        default: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-core-version }}
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.backend-root-path }} 
      - name: Build with dotnet
        run: dotnet build ${{ inputs.backend-root-path }} --configuration ${{ inputs.configuration }} --no-restore

      - name: Test
        run: dotnet test ${{ inputs.backend-root-path }} --logger "console;verbosity=detailed"

      - name: dotnet publish
        run: dotnet publish ${{ inputs.backend-root-path }}/${{ inputs.project-relative-path }} --configuration ${{ inputs.configuration }} --output ${{ inputs.azure-webapp-package-path }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.azure-webapp-package-path }}
